# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a2f853ca7de390c046260990207a3f556e9679ee02c4e46d9793969f1b32ac53488f4d6a9c9daea6db53af3fb33e07f0dc51016dcc53b68386c1c062cfe2dfe

test:
  secret_key_base: 34bb8411fe1345100b3800ce496b834f404de62948994ae7626ee3303bbf6486826bcdb3e923c0ffc63454d3af0bd5ec71439b7b0781ec161c0f3a3a12b62876

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
